export enum ActionType {
  INCREMENT = 'COUNTER/INCREMENT',
  RESET = 'COUNTER/RESET',
  SET_MIN_COUNTER = 'COUNTER/SET_MIN_COUNTER',
  SET_MAX_COUNTER = 'COUNTER/SET_MAX_COUNTER',
  SET_COUNTER = 'COUNTER/SET_COUNTER',
  SET_ERROR = 'COUNTER/SET_ERROR',
  ACTIVATE_SETTER = 'COUNTER/ACTIVATE_SETTER',
}
